defaults:
  - data: burgers_128
  - model/physical: burgers
  - model/synthetic: unet
  - trainer: synthetic
  - generation: default
  - evaluation: default
  - logging: default
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
  - optional experiment: ???  # Specify with experiment=name
  - _self_

run_params:
  experiment_name: ???  # Must be specified
  notes: ""
  mode: [train]
  model_type: synthetic

project_root: ${hydra:runtime.cwd}